packages:
    - "Dependency/Biome/NPM/**"
    - "Dependency/Microsoft/NPM/**"
    - "Dependency/OXC/NPM/**"
    - "Dependency/Rolldown/NPM/**"
    - "Dependency/SWC/NPM/**"
    - "Dependency/Tauri/NPM/**"
    - "Dependency/Vercel/NPM/**"

    - "Element/**"
